#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
  if [[ "${remote_ref##refs/heads/}" = 'master' ]]; then
    echo '[warn] Remote is master you know!? [y/N]'
    exec < /dev/tty
    read answer
    case $answer in
        'y' | 'yes') echo '[info] OK. Check local and remote branch name.';;
        * ) echo '[error] push failed.';exit 1;;
    esac
  fi
  if [[ $local_ref = $remote_ref ]]; then
    echo '[warn] push to remote, continue? [y/N]'
    exec < /dev/tty
    read answer
    case $answer in
        'y' | 'yes') echo '[info] OK. push start.';;
        * ) echo '[error] push failed.';exit 1;;
    esac
    exit 0
  else
    echo "$remote_ref is different from current branch."
    echo "Switch branch and Check git diff."
  fi
  exit 1
done

