version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.6
        environment:
          RAILS_ENV: test
          DB_USER: 2suke
          DB_PASSWORD: passw0rd
          DB_HOST: 127.0.0.1
          TZ: "Japan"
      - image: circleci/mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: railsci_test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_USER: 2suke
          MYSQL_PASSWORD: passw0rd
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update bundler
          command: |
            gem update --system
            gem install bundler
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: wait DB connection
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: DB setup
          command: rails db:create
      - run: rails db:migrate
      - run:
          name: rspec
          command: bundle exec rspec
